apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi
          image: fastapi-dakgalbi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: PORT
              value: "80"
