apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: k8s-system
spec:
  type: LoadBalancer
  selector:
    app: airflow
    component: webserver
  ports:
    - port: 8080
      targetPort: 8080
