apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      containers:
        - name: webserver
          image: airflow-manager:latest
          imagePullPolicy: Never
          command: ["airflow", "webserver"]
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: mysql-connection
            - name: _AIRFLOW_WWW_USER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: airflow-admin-username
            - name: _AIRFLOW_WWW_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: airflow-admin-password
