apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler-worker
  namespace: k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler-worker
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler-worker
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:latest
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "mysql://root:admin@mysql-service.k8s-system:3306/airflowdb"
        - name: worker
          image: apache/airflow:latest
          command: ["airflow", "celery", "worker"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "mysql://root:admin@mysql-service.k8s-system:3306/airflowdb"
