apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      containers:
        - name: webserver
          image: apache/airflow:latest
          command: ["airflow", "webserver"]
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "mysql://root:admin@mysql-service.k8s-system:3306/airflowdb"
