apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler-worker
  namespace: k8s-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler-worker
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler-worker
    spec:
      containers:
        - name: scheduler
          image: airflow-manager:latest
          imagePullPolicy: Never
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: mysql-connection
        - name: worker
          image: airflow-manager:latest
          imagePullPolicy: Never
          command: ["airflow", "celery", "worker"]
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: mysql-connection
