apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
  namespace: k8s-system
spec:
  template:
    spec:
      containers:
        - name: airflow-db-init
          image: apache/airflow:2.10.2
          command: ["airflow", "db", "init"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: mysql-connection
      restartPolicy: Never
  backoffLimit: 4
